name: Build and Release Plugin

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version (e.g., 1.0.0)'
        required: true
      changelog:
        description: 'Changelog'
        required: true
        type: string
      prerelease:
        description: 'Is this a prerelease? (true/false)'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Update version in pom.xml
        run: |
          sed -i 's|<version>.*</version>|<version>${{ inputs.version }}</version>|' pom.xml

      - name: Build with Maven
        run: mvn clean package

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: target/*.jar
          tag_name: v${{ inputs.version }}
          name: Release v${{ inputs.version }}
          body: "${{ inputs.changelog }}"
          draft: false
          prerelease: ${{ inputs.prerelease }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
