name: Build and Release Plugin

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Repository auschecken
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build mit Maven
        run: mvn clean package

      - name: Version aus `pom.xml` extrahieren
        id: get_version
        run: echo "VERSION=$(awk -F '[<>]' '/<version>/ {print $3; exit}' pom.xml)" >> $GITHUB_ENV

      - name: Release erstellen
        uses: softprops/action-gh-release@v1
        with:
          files: target/*.jar
          tag_name: v${{ env.VERSION }}
          name: Release v${{ env.VERSION }}
          body: "Automatisches Release von Commit ${{ github.sha }}"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Lösche Branch nach Merge
        if: github.ref == 'refs/heads/master'
        run: |
          git push origin --delete ${{ github.head_ref }}
